### ISSUE TITLE
can not run the GUI

### ISSUE THREAD

**Issue by Four-Fire** [oyvindlr/MRI-RGB-Simulator#1]
Hi! oyvindlr. Nice work but i cann't run the GUI code. The information of error are below: 
----------------------------------------------------------------
The name parallel.pool.Dataqueue cannot be resolved.

Error ParForWaitbarCreateMH (line 11)
hWaitbarMsgQueue = parallel.pool.DataQueue;

Error mriGUI /RunButtonPushed (line 223)
[hWaitbar,progress]=
ParForWaitbarCreateMH("Processing",3*nloops/1000); app.vals
= readSettings(app, 'R');

Error using the matlab.ui.control.internal.controller.Com ponentController/executeUserCallback (line 410)
An error occurred while computing Button PrivateButtonPushedFcn.

**Comment by oyvindlr** [comment]
Hi @Four-Fire, this is probably because you do not have the parallel processing toolbox for Matlab installed.  If possible, I recommend installing it, since the application will otherwise be very slow. 

The error is caused by the "ParForWaitBar", which is a third party component from the Mathworks file exchange.

It should be relatively easy to switch to a "normal" waitbar when the parallel toolbox is unavailable.

**Comment by Four-Fire** [comment]
Thanks a lot!

**Comment by oyvindlr** [comment]
Hi again @Four-Fire, I have tried to fix this issue. Try to download the code again and see if it works without the parallel computing toolbox now.

**Comment by Four-Fire** [comment]
Hi @oyvindlr, I have downloaded the new code but it does not work without the parallel computing toolbox.

**Comment by oyvindlr** [comment]
@Four-Fire , what is the error message? The same as last time?

**Comment by Four-Fire** [comment]
Yes, same as last time.

**Comment by oyvindlr** [comment]
Sorry about that, since I have the toolbox I wasn't able to test without it! I have updated again now, so you can see if you get it to work.

**Comment by Four-Fire** [comment]
hahaha, it's ok. I have installed the toolbox and the code have worked when I applied to you "Thanks a lot ".  I'm sorry I didn't express myself correctly.

**Comment by Four-Fire** [comment]
And by the way, the toolbox can be uninstalled in matlab, maybe in the "additional function"

**Comment by oyvindlr** [comment]
Great! Anyway, nice that I got to fix that issue (hopefully). 
I'm glad someone took interest in this project! I did it as project in a course on medical imaging, and thought it was a nice start. But it needs some love and some more advanced features to be really useful I think.

**Comment by Four-Fire** [comment]
"Well begun is half done." I think the project is a great work because MRI simulation is a hard project(at least for me HaHaHa).
